def options(opt):
	pass

def configure(conf):
	conf.check_cc(msg = 'Checking for SEEK_HOLE/SEEK_DATA',
		      fragment='''
				#include <unistd.h>
				int main()
				{
					lseek(-1, 0, SEEK_DATA);
					lseek(-1, 0, SEEK_HOLE);
					return 0;
				}''',
		      mandatory=True)

def build(bld):
	bld.stlib(source='''cli_path.c cli_util.c cli_put.c
			    cli_get.c cli_del.c cli_create.c cli_cp.c cli_ls.c
			    cli_stat.c''',
		  target='cli_lib',
		  use=['elasto_core'],
		  includes = '. ..')
	bld.program(source='elasto_client.c',
		    target='elasto_cli',
		    lib=['crypto', 'expat', 'ssl'] + bld.env.LIBEVENT_LIBS,
		    use=['elasto_file', 'cli_lib', 'linenoise'],
		    includes = '. ..',
		    install_path = '${BINDIR}')
