def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')
	conf.env.append_unique('CFLAGS', ['-Wall'])

def build(bld):
	bld.stlib(source='list/list.c', target='libccan')

