def options(opt):
        opt.add_option('--with-tcmu', action='store_true', default=False,
                       help='build with tcmu-runner support (deprecated)')

def configure(conf):
        conf.env.WITH_TCMU = conf.options.with_tcmu
        if conf.env.WITH_TCMU == True:
                print("WARNING: elasto_tcmu is deprecated!")
                conf.check(lib='tcmu', mandatory=True)

def build(bld):
        if bld.env.WITH_TCMU == False:
                return
        bld.program(source='consumer.c',
                    target='elasto_tcmu',
                    lib=['crypto', 'expat', 'ssl', 'tcmu', 'pthread']
                        + bld.env.LIBEVENT_LIBS,
                    use=['elasto_file', 'elasto_wq'],
                    includes = '. ..',
                    install_path = '${BINDIR}')
        bld.install_as('${BINDIR}/elasto_tcmu_configfs',
                       'elasto_tcmu_configfs.sh')
