def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')
	if not conf.check(lib='tcmu', mandatory=False):
		conf.env.SKIP_TCMU = "yes"

def build(bld):
	if bld.env.SKIP_TCMU in ["yes"]:
		print("Skipping elasto_tcmu build: tcmu library required")
		return
	bld.program(source='consumer.c',
		    target='elasto_tcmu',
		    lib=['crypto', 'expat', 'ssl', 'tcmu']
			+ bld.env.LIBEVENT_LIBS,
		    use=['elasto_file'],
		    includes = '. ..',
		    install_path = '${BINDIR}')
