recurse_subdirs = 'azure amazon local'

def options(opt):
	opt.recurse(recurse_subdirs)

def configure(conf):
	conf.recurse(recurse_subdirs)

def build(bld):
	bld.shlib(source='''handle.c io.c open.c xmit.c dir.c lease.c
			    stat.c token.c''',
		  target='elasto_file',
		  vnum=bld.env.LIBELASTO_API_VERS,
		  lib=['crypto', 'expat', 'ssl', 'dl'] + bld.env.LIBEVENT_LIBS,
		  use=['elasto_core'],
		  includes = '. .. ../../')
	bld.install_as('${INCLUDEDIR}/elasto/file.h', 'file_api.h')
	bld(features="subst",
	    source="elasto_file.pc.in",
	    target="elasto_file.pc",
	    install_path="${LIBDIR}/pkgconfig")
	bld.recurse(recurse_subdirs)
